services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

    huh.cleaner.command.minutely:
      public: true
      class: HeimrichHannot\CleanerBundle\Command\CleanerCommand
      calls:
        - method : setInterval
          arguments:
          - '%huh.command.minutely%'
      arguments:
        - "@contao.framework"
    huh.cleaner.command.hourly:
      public: true
      class: HeimrichHannot\CleanerBundle\Command\CleanerCommand
      calls:
          - method : setInterval
            arguments:
              - '%huh.command.hourly%'
      arguments:
        - "@contao.framework"
    huh.cleaner.command.daily:
      public: true
      class: HeimrichHannot\CleanerBundle\Command\CleanerCommand
      calls:
          - method : setInterval
            arguments:
              - '%huh.command.daily%'
      arguments:
        - "@contao.framework"
    huh.cleaner.command.weekly:
      public: true
      class: HeimrichHannot\CleanerBundle\Command\CleanerCommand
      calls:
         - method : setInterval
           arguments:
           - '%huh.command.weekly%'
      arguments:
        - "@contao.framework"