services:
  _defaults:
    autoconfigure: true
    autowire: true

  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - [ "setFramework", [ "@contao.framework" ] ]

  huh.cleaner.command.minutely:
    public: true
    class: HeimrichHannot\CleanerBundle\Command\CleanerCommand
    calls:
      - method: setInterval
        arguments:
          - '%huh.command.minutely%'
  huh.cleaner.command.hourly:
    public: true
    class: HeimrichHannot\CleanerBundle\Command\CleanerCommand
    calls:
      - method: setInterval
        arguments:
          - '%huh.command.hourly%'
  huh.cleaner.command.daily:
    public: true
    class: HeimrichHannot\CleanerBundle\Command\CleanerCommand
    calls:
      - method: setInterval
        arguments:
          - '%huh.command.daily%'
  huh.cleaner.command.weekly:
    public: true
    class: HeimrichHannot\CleanerBundle\Command\CleanerCommand
    calls:
      - method: setInterval
        arguments:
          - '%huh.command.weekly%'
