parameters:
  huh.command.minutely: minutely
  huh.command.hourly: hourly
  huh.command.daily: daily
  huh.command.weekly: weekly

services:
  _defaults:
    bind:
      $projectDir: '%kernel.project_dir%'

  huh.cleaner.registry.cleaner:
    public: true
    class: HeimrichHannot\CleanerBundle\Registry\CleanerRegistry
    arguments:
      - "@contao.framework"
  huh.cleaner.controller.poormanscron:
      public: true
      class: HeimrichHannot\CleanerBundle\Controller\PoorManCronController
      autowire: true